language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
cache:
  directories:
    - deps
  pip: true
script:
  - python manage.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
