language: python
python:
  - '3.6'
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
  - flake8 . --exclude=migrations,cms/settings
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
