config:
  target: 'https://www.good-thinking.uk'
  phases:
    - duration: 1
      arrivalRate: 8
    - duration: 30
      arrivalCount: 30
scenarios:
  - flow:
    - get:
        url: "/"
    - get:
        url: "/anxious/"
    - get:
        url: "/resources/chill-panda/"
  - flow:
    - get:
        url: "/"
    - get:
        url: "/sleep-deprived/"
    - get:
        url: /resources/sleepytime/
    - get:
        url: "/sleep-deprived/"
    - get:
        url: "/resources/great-british-sleep-survey/"
    - get:
        url: "/feedback/"
  - flow:
    - get:
        url: "/self-assessment/"
    - get:
        url: "/self-assessment/#assessment-container"
    - get:
        url: "/assessment-summary/"
    - get:
        url: "/crisis/"
