branch-defaults:
  master:
    environment: GoodThinkingProdDocker
    group_suffix: null
  aws-eb-docker-uwsgi:
    environment: GoodThinkingProdDocker
    group_suffix: null
global:
  application_name: Good Thinking Prod
  branch: null
  default_ec2_keyname: aws_good_thinking_prod
  default_platform: Python 3.4
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: mindwaves
  repository: null
  sc: git
  workspace_type: Application
